# -*- coding: utf-8 -*-
"""Optimizing_ETA_with_GBI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10bqiTQ0nVFtQaPyJxG_j83C5etfAExoJ
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

FILE_PATH = 'delivery_data.csv'
df = pd.read_csv(FILE_PATH)

"""# Data Cleaning"""

print("=" * 50)
print("DATASET OVERVIEW")
print("=" * 50)

print(f"\nShape of Dataset : {df.shape}")
print(f"Total Elements   : {df.size}")

#col info

print("\n" + "=" * 50)
print("COLUMN NAMES")
print("=" * 50)

for col in df.columns:
    print(f"- {col}")

#data types

print("\n" + "=" * 50)
print("DATA TYPES")
print("=" * 50)

print(df.dtypes)


#missing vals


print("\n" + "=" * 50)
print("MISSING VALUES")
print("=" * 50)

print(df.isnull().sum())

# 1st 5rows

print("\n" + "=" * 50)
print("FIRST 5 ROWS")
print("=" * 50)

print(df.head())


#statistical summary


print("\n" + "=" * 50)
print("STATISTICAL SUMMARY")
print("=" * 50)

print(df.describe())

#complete df info

print("\n" + "=" * 50)
print("DATAFRAME INFO")
print("=" * 50)

df.info()

# ----------------------------------------------------------
# SECTION 2 — Understand the Data (Mental Model)
# ----------------------------------------------------------
# CONCEPT:
#   Each ROW is one SEGMENT of a multi-leg delivery trip.
#   Multiple rows share the same trip_uuid — they are legs of the same journey.
#
#   Key columns:
#   - segment_actual_time  : how long this segment actually took (minutes)
#   - segment_osrm_time    : what the GPS engine predicted (minutes)
#   - segment_factor       : ratio = actual / osrm  → >1 means delayed
#   - route_type           : FTL (full truckload) or Carting (multi-drop)
#   - source_center / destination_center : facility IDs (will become graph NODES)
#   - segment_osrm_distance: road distance in km

print("\n=============Route type================== ")
print(df['route_type'].value_counts())

print("\nsegemnt factor or delay ratio\n")
print(f"mean :{df['segment_factor'].mean()}")
# 1.0 = on time
print(f"median :{df['segment_factor'].median()}")
print(f"max :{df['segment_factor'].max()}")
print(f"min :{df['segment_factor'].min()}")
# significant delay -> factor > 1.2
print(f"percentage of shipment delayed significantly :{ (df['segment_factor']>1.2).mean() * 100} %")

# SECTION 3 — Data Cleaning

# remove duplicates
df[df.duplicated()]
# no duplicates

#min was -ve -> remove -ve time
neg = (df.select_dtypes (include=np.number) <=0).sum()
print(neg)

df[df['segment_factor'] <= 0][[
    'segment_actual_time',
    'segment_osrm_time',
    'segment_factor'
]]

# delete rows with -ve segment_actual_time and segment_factor = just remove rows with -ve segment_factor
rb=df.shape[0]
df = df[df['segment_factor'] > 0]

ra=df.shape[0]
print(f"removed {rb - ra} rows with negative/zero segment_factor")

# max segment_factor was 574 --> this is too big of a value -> CAP THE VALUE

# WHY: segment_factor = 574 means a segment took 574× longer than expected.
#      Even the worst traffic jam won't do that — these are data errors
#      (double scans, truck breakdowns logged as delays, re-entry mistakes).
#      Keeping them makes your mean delay ratio explode and misleads the model.

# Because very large values are usually:
# corrupted scans,failed shipments,operational anomalies,bad logs.

# THRESHOLD CHOICE: 10 is conservative but defensible.
#      A factor of 10 (segment took 10× OSRM estimate) is already a severe delay.
#      Alternative: use 99th percentile → df['segment_factor'].quantile(0.99)
#      We chose a hard cap so the threshold is interpretable and explainable.

CAP=10
rb=df.shape[0]

df=df[df['segment_factor']<=CAP]

ra=df.shape[0]
print(f"rows removed : {rb-ra}")
print(f"rows remaining: {ra}")

# handling missing values

# some source/destination name are missing
# but cant be dropped
# as they might be connecting actual src to dest
# and we have all the center codes
# we can drop the column though, since those are just names only

df.isnull().sum()

# filling missing src/ dest with center codes

df['source_name'] = df['source_name'].fillna(df['source_center'])
df['destination_name'] = df['destination_name'].fillna(df['destination_center'])
print(df.isnull().sum())

"""# Feature Engineering"""

for c in ["trip_creation_time", "od_start_time", "od_end_time", "cutoff_timestamp"]:
    df[c] = pd.to_datetime(df[c], errors="coerce")
time_ref = df["cutoff_timestamp"].fillna(df["od_start_time"])
df["departure_hour"]        = time_ref.dt.hour.fillna(12).astype(int)
df["departure_day_of_week"] = time_ref.dt.dayofweek.fillna(2).astype(int)
df["hour_sin"]              = np.sin(2 * np.pi * df["departure_hour"] / 24)
df["hour_cos"]              = np.cos(2 * np.pi * df["departure_hour"] / 24)
df["is_night_shipment"]     = df["departure_hour"].apply(lambda h: 1 if (h < 6 or h >= 22) else 0)
df["is_weekend"]            = df["departure_day_of_week"].apply(lambda d: 1 if d >= 5 else 0)
df["is_delayed"]            = (df["segment_factor"] > 1.2).astype(int)
df["route_type_encoded"]    = (df["route_type"] == "FTL").astype(int)
df["is_cutoff"]             = df["is_cutoff"].astype(int)
df["osrm_speed_kmh"] = np.where(
    df["segment_osrm_time"] > 0,
    df["segment_osrm_distance"] / (df["segment_osrm_time"] / 60),
    np.nan,
)
def _tod(h):
    if 6  <= h < 12: return "Morning"
    if 12 <= h < 18: return "Afternoon"
    if 18 <= h < 22: return "Evening"
    return "Night"
df["time_of_day"] = df["departure_hour"].apply(_tod)
# Verify the fix worked
print(f"Weekend shipments: {df['is_weekend'].mean()*100:.1f}%")
print(f"Night shipments:   {df['is_night_shipment'].mean()*100:.1f}%")
print(f"time_of_day distribution:\n{df['time_of_day'].value_counts(normalize=True).round(3)}")

# is_delayed
# WHY: This is a TARGET LABEL for classification tasks.
#      If actual time > 1.2× osrm prediction, we call the segment "delayed".
#      The 20% threshold (1.2×) comes directly from the PS definition of SLA breach.
#
# USAGE: You can also use segment_factor directly as a regression target.
#        is_delayed turns it into a yes/no classification problem.

# TARGET VARIABLE ONLY

DELAY_THRESHOLD = 1.2

df['is_delayed'] = (df['segment_factor'] > DELAY_THRESHOLD).astype(int)
delay_percent=df['is_delayed'].mean()*100
print(f" {delay_percent:.1f}% of segments are delayed")

# ── Feature 4.6 — distance_gap (CORRECTED) ───────────────
# WHY: Measures how much the actual path deviated from OSRM's estimate.
#      Both actual_distance_to_destination and osrm_distance are CUMULATIVE
#      distances from the start of the current OD leg (verified from raw data).
#      Subtracting same-granularity columns gives a meaningful route deviation.
#
# IMPORTANT: The old version subtracted segment_osrm_distance (per-interval)
#   from actual_distance_to_destination (cumulative). That was a granularity
#   mismatch — the result was ~99% correlated with the cumulative term alone.
#
# NOTE: This feature uses post-hoc actual distance. It is valid for
#   understanding route deviation patterns but may not be available at
#   prediction time for future trips. Keep for EDA; validate before ML use.

df['distance_gap'] = (df['actual_distance_to_destination']
                      - df['osrm_distance'])
print(f"distance_gap created mean: {df['distance_gap'].mean():.2f} km")

#FOR EDA ONLY -> NOT FOR ML MODEL

#actual_distance_to_destination is systematically smaller than osrm_distance in every single row.

#Why?
#Despite the misleading column name, actual_distance_to_destination appears to be a straight-line (geodesic) distance
#the crow-flies distance from origin to the current point. Meanwhile osrm_distance is the road-network distance
#the actual path along roads.
#Roads are never straight. They curve, go around mountains, follow city grids.
#So road distance is always longer than straight-line distance. The typical ratio is 0.80–0.87, which matches what we see.
#What the negative gap means in business terms:
#The gap measures route circuitousness (how winding the road is vs a straight line)
#A value of −50 km means "the road route is 50 km longer than a direct line"
#More negative = more winding/indirect route (mountains, urban grid)
#Less negative (closer to 0) = route is relatively direct (highways)

# route_type_encoded
# WHY: ML models work with numbers, not text.
#      FTL = 1, Carting = 0 (binary encoding).

df['route_type_encoded'] = (df['route_type'] == 'FTL').astype(int)
df.head()

# osrm_speed_assumption
# WHY: The speed that OSRM assumed for this interval.
#      Reveals whether OSRM treated this segment as highway vs urban road.
#      HIGH value = OSRM thinks it's a fast corridor (highway).
#      LOW value  = OSRM thinks it's slow (urban, mountain).
#      This is SAFE — computed entirely from pre-trip OSRM estimates.

df['osrm_speed_kmh'] = np.where(
    df['segment_osrm_time'] > 0,
    df['segment_osrm_distance'] / (df['segment_osrm_time'] / 60),  # km/h
    np.nan
)
print(f"osrm_speed_kmh median: {df['osrm_speed_kmh'].median():.1f} km/h")

# corridor_id
# WHY: Unique ID for each (source → destination, route_type) combination.
#      This becomes the key for graph edge weights and corridor aggregation.

#only for graph

df['corridor_id'] = (df['source_center'] + '_'+ df['destination_center'] + '_'+ df['route_type'])

n_corridors = df['corridor_id'].nunique()
print(f"[4.9] corridor_id created — {n_corridors:,} unique corridors in the network")

#Feature Selection

# TRAIN/TEST SPLIT BEFORE DROPPING 'data'
# The dataset has a pre-defined split in the 'data' column:

train_mask = df['data'] == 'training'
test_mask  = df['data'] == 'test'

print(f"Pre-defined split from dataset:")
print(f"  Training rows: {train_mask.sum():,}  ({train_mask.mean()*100:.1f}%)")
print(f"  Test rows    : {test_mask.sum():,}  ({test_mask.mean()*100:.1f}%)")

#DROP COLUMNS

columns_to_drop = [

    # Dataset bookkeeping
    'data',

    # Internal IDs
    'route_schedule_uuid',

    # Human-readable labels (redundant with center codes)
    'source_name',
    'destination_name',

    # Cutoff timestamp (raw datetime, not useful directly)
    'cutoff_timestamp',

    # Post-hoc information (not known before trip completion)
    'od_end_time',
    'actual_time',
    'factor',
    'start_scan_to_end_scan',

    # Redundant cumulative estimate
    'osrm_time',
]



# Drop only columns that actually exist
cols_to_drop_existing = [col for col in columns_to_drop if col in df.columns]

# Create MODEL DATASET
# df remains untouched. df_model is for graph building and ML.
df_model = df.drop(columns=cols_to_drop_existing)

print(f"\nDropped {len(cols_to_drop_existing)} columns:")
print(cols_to_drop_existing)
print(f"\nRemaining columns: {df_model.shape[1]}")
print(f"Final dataset shape: {df_model.shape}")


#DEFINE TARGETS
# These columns exist in df_model but must NEVER be used as input features.
# They are the quantities we are trying to predict.

REGRESSION_TARGET     = 'segment_actual_time'   # predict delivery time in minutes
CLASSIFICATION_TARGET = 'is_delayed'            # predict SLA breach (yes/no)
SECONDARY_TARGET      = 'segment_factor'        # predict delay ratio

print(f"\n--- Targets (DO NOT use as features) ---")
print(f"  Regression     : {REGRESSION_TARGET}")
print(f"  Classification : {CLASSIFICATION_TARGET}")
print(f"  Secondary      : {SECONDARY_TARGET}")


# SPLIT df_model INTO TRAIN / TEST
# Apply the masks we saved BEFORE dropping 'data'.

df_train = df_model[train_mask].reset_index(drop=True)
df_test  = df_model[test_mask].reset_index(drop=True)

print(f"  df_train: {df_train.shape[0]:,} rows × {df_train.shape[1]} columns")
print(f"  df_test : {df_test.shape[0]:,} rows × {df_test.shape[1]} columns")

print("\nColumns retained:")
print(sorted(df_model.columns.tolist()))


#Corridor aggregation features

# RULE: compute on df_train ONLY, then join to BOTH train and test.
# If you compute on the full df, test-set info leaks into training.

print("\n\nSTAGE 5: CORRIDOR FEATURES")

corridor_stats = df_train.groupby('corridor_id').agg(
    corridor_median_delay = ('segment_factor', 'median'),
    corridor_mean_delay   = ('segment_factor', 'mean'),
    corridor_delay_std    = ('segment_factor', 'std'),    # variability
    corridor_trip_volume  = ('trip_uuid', 'nunique'),      # how busy  #number of unique trips
    corridor_pct_delayed  = ('is_delayed', 'mean'),        # reliability
).reset_index()

# Join to both sets — left join so unseen corridors in test get NaN
df_train = df_train.merge(corridor_stats, on='corridor_id', how='left')
df_test  = df_test.merge(corridor_stats,  on='corridor_id', how='left')

# Fill NaN for unseen corridors in test (use global train median as fallback)
global_median = df_train['corridor_median_delay'].median()
df_test['corridor_median_delay'].fillna(global_median, inplace=True)
df_test['corridor_mean_delay'].fillna(df_train['corridor_mean_delay'].median(), inplace=True)
df_test['corridor_pct_delayed'].fillna(df_train['corridor_pct_delayed'].median(), inplace=True)
df_test['corridor_trip_volume'].fillna(0, inplace=True)
df_test['corridor_delay_std'].fillna(df_train['corridor_delay_std'].median(), inplace=True)

print(f"Corridor features added. Sample:")
print(df_train[['corridor_id','corridor_median_delay','corridor_pct_delayed','corridor_trip_volume']].head(3))
print(f"\ndf_train shape: {df_train.shape}")
print(f"df_test  shape: {df_test.shape}")

# Visualisations

fig, axes = plt.subplots(2, 2, figsize=(14, 10))
fig.suptitle("PS4: Cleaned Data — Key Distributions", fontsize=15, fontweight='bold')

# Plot 1: Distribution of segment_factor (the delay ratio)
axes[0, 0].hist(df_model['segment_factor'], bins=50, color='steelblue', edgecolor='white')
axes[0, 0].axvline(1.0, color='green', linestyle='--', label='On time (factor=1)')
axes[0, 0].axvline(1.2, color='red', linestyle='--', label='SLA breach (1.2)')
axes[0, 0].set_title("Delay Factor Distribution")
axes[0, 0].set_xlabel("segment_factor  (actual / osrm)")
axes[0, 0].set_ylabel("Count")
axes[0, 0].legend()

# Plot 2: Delay rate by hour of day
hourly_delay = df_model.groupby('departure_hour')['is_delayed'].mean() * 100
axes[0, 1].bar(hourly_delay.index, hourly_delay.values, color='coral')
axes[0, 1].set_title("% Delayed Segments by Departure Hour")
axes[0, 1].set_xlabel("Hour of Day (0–23)")
axes[0, 1].set_ylabel("% Delayed")
axes[0, 1].axhline(hourly_delay.mean(), color='black', linestyle='--', label='Mean')
axes[0, 1].legend()

# Plot 3: FTL vs Carting — segment_factor comparison
for route, color in [('FTL', 'steelblue'), ('Carting', 'orange')]:
    subset = df_model[df_model['route_type'] == route]['segment_factor']
    axes[1, 0].hist(subset, bins=50, alpha=0.6, label=route, color=color)
axes[1, 0].set_title("Delay Factor: FTL vs Carting")
axes[1, 0].set_xlabel("segment_factor")
axes[1, 0].set_ylabel("Count")
axes[1, 0].legend()

# Plot 4: Correlation heatmap — SAFE features only (no target-derived)
corr_cols = ['segment_factor', 'segment_osrm_time', 'segment_osrm_distance',
             'osrm_speed_kmh', 'departure_hour', 'is_night_shipment',
             'is_weekend', 'route_type_encoded']
corr_matrix = df_model[corr_cols].corr()
sns.heatmap(corr_matrix, annot=True, fmt='.2f', cmap='coolwarm',
            ax=axes[1, 1], center=0)
axes[1, 1].set_title("Feature Correlation Matrix (safe features)")

plt.tight_layout()
plt.savefig('ps4_eda_plots.png', dpi=150, bbox_inches='tight')
plt.show()
print("Plots saved as ps4_eda_plots.png")

"""# Section - Graph Making"""


#trip-level data into corridor-level
#Stratified corridor aggregation (strata=subgroups)

import networkx as nx

#A stratum means a subgroup.
stratum_stats=(
    df_train.groupby(["source_center","destination_center","route_type","time_of_day"])
    .agg(stratum_median_delay = ("segment_factor",       "median"),
         stratum_mean_delay   = ("segment_factor",       "mean"),
         stratum_std_delay    = ("segment_factor",       "std"),
         stratum_pct_delayed  = ("is_delayed",           "mean"),
         stratum_trip_volume  = ("trip_uuid",            "nunique"),
         stratum_avg_minutes  = ("segment_actual_time",  "mean"))
    .reset_index()
)

print(f"Stratum level rows: {len(stratum_stats):,}  "
      f"(was {len(corridor_stats):,} at corridor level)")

#origin destination stats
od_stats = (
    df_train
    .groupby(["source_center","destination_center"])
    .agg(median_delay = ("segment_factor",      "median"),
         mean_delay   = ("segment_factor",      "mean"),
         std_delay    = ("segment_factor",      "std"),
         pct_delayed  = ("is_delayed",          "mean"),
         trip_volume  = ("trip_uuid",           "nunique"),
         avg_minutes  = ("segment_actual_time", "mean"))
    .reset_index()
)
print(f"Unique OD pairs (graph edges): {len(od_stats):,}")

# graph building (directed and weighted)

#stratum_stats=Detailed corridor information
#od_stats=One summary per corridor
#G=complete logistics corridor

G=nx.DiGraph()

strata_by_od={} # to store detailed corridor info before creating graph edges
#For one (source, destination) pair, it stores all route-type and time-of-day variations.

#read stratum_stats
for (src, dst, rt, tod), grp in stratum_stats.groupby(
        ["source_center","destination_center","route_type","time_of_day"]):
    strata_by_od.setdefault((src, dst), {})[(rt, tod)] = {
        "median_delay": float(grp["stratum_median_delay"].iloc[0]),
        "pct_delayed":  float(grp["stratum_pct_delayed"].iloc[0]),
        "trip_volume":  int(grp["stratum_trip_volume"].iloc[0]),
        "avg_minutes":  float(grp["stratum_avg_minutes"].iloc[0]),
    }


# iterrows() returns (index, row) for each row in od_stats
# '_' ignores the index since we don't need it; 'row' contains corridor data
# For eac h OD pair, create a directed edge and attach corridor statistics as edge attributes

for _, row in od_stats.iterrows():
    src, dst = row["source_center"], row["destination_center"]
    G.add_edge(
        src, dst,
        weight        = float(row["median_delay"]),
        mean_delay    = float(row["mean_delay"]),
        delay_std     = 0.0 if np.isnan(row["std_delay"]) else float(row["std_delay"]),
        pct_delayed   = float(row["pct_delayed"]),
        trip_volume   = int(row["trip_volume"]),
        avg_minutes   = float(row["avg_minutes"]),
        strata        = strata_by_od.get((src, dst), {}),
    )


# nodes = facilities/hubs
# edges = source→destination corridors

print(f"Graph built, nodes: {G.number_of_nodes():,}  edges: {G.number_of_edges():,}")
print(f"Average out degree: {sum(d for _, d in G.out_degree())/G.number_of_nodes():.2f}")
print(f"Density:            {nx.density(G):.5f}")

weak = list(nx.weakly_connected_components(G))
print(f"Weaklynconnected components: {len(weak)}   "
      f"(largest = {max(len(c) for c in weak):,} nodes, "
      f"isolated = {sum(1 for c in weak if len(c)==1):,})")

# Weakly connected component:
# if edge directions are ignored, can hubs still reach each other?
# largest = size of main logistics network
# isolated = facilities disconnected from the rest of the network

# graph visual

import matplotlib.pyplot as plt

TOP_N = 40

# finding top 40 hubs for visualization

top_nodes = (
    pd.Series({n: sum(G[n][v]["trip_volume"] for v in G.successors(n))
               for n in G.nodes()})
    .sort_values(ascending=False).head(TOP_N).index.tolist()
)


# creating a subgraph
H = G.subgraph(top_nodes).copy()


#Spring Layout = physics simulation.
#Nodes = balls   Edges = springs

pos = nx.spring_layout(H, seed=42, k=0.6)
fig, ax = plt.subplots(figsize=(13, 9))
nx.draw_networkx_edges(
    H, pos,
    width=[H[u][v]["trip_volume"] ** 0.4 * 0.05 for u, v in H.edges()],
    edge_color=[H[u][v]["weight"] for u, v in H.edges()],
    edge_cmap=plt.cm.RdYlGn_r, edge_vmin=0.9, edge_vmax=1.6,
    arrows=True, arrowsize=8, alpha=0.7, ax=ax,
)
nx.draw_networkx_nodes(
    H, pos,
    node_size=[200 + sum(H[n][v]["trip_volume"] for v in H.successors(n)) ** 0.5
               for n in H.nodes()],
    node_color="#1f77b4", alpha=0.9, ax=ax,
)
nx.draw_networkx_labels(H, pos, font_size=7, ax=ax)
ax.set_title(f"Top-{TOP_N} hubs by outbound volume\n"
             "Edge colour = median delay factor (red = chronic), width = trip volume")
ax.axis("off")
plt.tight_layout()
plt.savefig("stage6_top_hubs_subgraph.png", dpi=150, bbox_inches="tight")
plt.show()

#stage 7 graph audit

#Betweenness - How many important routes pass through me?
#Betweenness identifies bottleneck hubs whose failure would disrupt many shortest-delay routes.





#Centrality battery

print("Computing centrality battery — ~30s on the full graph…")
# networkx returns object => convert to dictionary => in_degree[jaipur] is now valid
in_degree    = dict(G.in_degree())
out_degree   = dict(G.out_degree())
weighted_in  = dict(G.in_degree(weight="trip_volume"))
weighted_out = dict(G.out_degree(weight="trip_volume"))

G_und = G.to_undirected() # unidrected graph (for some statistics)


# how offen path pass through a city/node
#Delhi->Jaipur->Mumbai, Every route goes through Jaipur
#So Jaipur=High Betweenness
betweenness_n = nx.betweenness_centrality(G_und, weight="weight", normalized=True)

#How close to everybody else
closeness_n   = nx.closeness_centrality(G_und, distance="weight")

# PageRank:
# Recursive importance score.
# Important hubs receiving traffic from other important hubs rank higher.
#therefore : weight ="trip_volume"
pagerank_n    = nx.pagerank(G, weight="trip_volume", alpha=0.85)

# Clustering Coefficient:
# Measures how connected a hub's neighbours are.
# High value = dense local mesh with alternate routes.
clustering_n  = nx.clustering(G_und, weight="weight")

# Edge Betweenness Centrality:
# Identifies critical corridors.
# High value = many shortest-delay paths depend on this edge.
edge_betw     = nx.edge_betweenness_centrality(G_und, weight="weight",
                                               normalized=True)
print("Centrality computed.")



# 7  SLA breach contribution per hub

# Graph centrality tells us which hubs are structurally important.
# These scores tell us which hubs are associated with delayed shipments.

# Formula: delay impact = pct_delayed × trip_volume

# A corridor with high delay and high shipment volume contributes more
# than a corridor with high delay but very few shipments.


# Measures the amount of delayed traffic a hub sends into the network.
# Higher score = hub is a larger source of SLA violations.
sla_breach_score = {
    n: sum(G[n][v]["pct_delayed"] * G[n][v]["trip_volume"]
           for v in G.successors(n)) # all outgoing corridors
    for n in G.nodes()
}

# Measures the amount of delayed traffic arriving at a hub.
# Higher score = hub receives more delayed shipments from upstream hubs.
inbound_breach_score = {
    n: sum(G[u][n]["pct_delayed"] * G[u][n]["trip_volume"]
           for u in G.predecessors(n)) # all incomming corridors
    for n in G.nodes()
}

# Hub summary table + composite bottleneck rank
node_df = pd.DataFrame({
    "hub_id"               : list(G.nodes()),
    "betweenness"          : [betweenness_n.get(n, 0)        for n in G.nodes()],
    "closeness"            : [closeness_n.get(n, 0)          for n in G.nodes()],
    "pagerank"             : [pagerank_n.get(n, 0)           for n in G.nodes()],
    "clustering"           : [clustering_n.get(n, 0)         for n in G.nodes()],
    "in_degree"            : [in_degree.get(n, 0)            for n in G.nodes()],
    "out_degree"           : [out_degree.get(n, 0)           for n in G.nodes()],
    "weighted_in"          : [weighted_in.get(n, 0)          for n in G.nodes()],
    "weighted_out"         : [weighted_out.get(n, 0)         for n in G.nodes()],
    "sla_breach_score"     : [sla_breach_score.get(n, 0)     for n in G.nodes()],
    "inbound_breach_score" : [inbound_breach_score.get(n, 0) for n in G.nodes()],
})


#pct -> converts data to 0->1 percentile score
# 40% structural risk + 35% SLA contribution + 15% propagation + 10% inbound
node_df["bottleneck_rank"] = (
    node_df["betweenness"]         .rank(pct=True) * 0.40 +
    node_df["sla_breach_score"]    .rank(pct=True) * 0.35 +
    node_df["pagerank"]            .rank(pct=True) * 0.15 +
    node_df["inbound_breach_score"].rank(pct=True) * 0.10
)

# Top Bottleneck Hub
node_df = node_df.sort_values("bottleneck_rank", ascending=False).reset_index(drop=True)

print("TOP 10 BOTTLENECK HUBS (composite rank):")
print(node_df.head(10)[
    ["hub_id","bottleneck_rank","betweenness","sla_breach_score",
     "pagerank","in_degree","out_degree"]
].to_string(index=False))
top5_hubs = node_df.head(5).copy()




# Critical and chronic corridors

# Build a corridor level table using edge betweenness
# and edge attributes from Stage 6.

# edge betweenness: Measures how often a corridor lies on shortest-delay paths.
# High value = critical corridor; removing it would disrupt many efficient routes.

edge_records = []
for (u, v), eb in edge_betw.items():

  # the original directed corridor
    if   G.has_edge(u, v): a, b = u, v
    elif G.has_edge(v, u): a, b = v, u
    else: continue
    edge_records.append({
        "src": a, "dst": b, "edge_betweenness": eb,
        "median_delay": G[a][b]["weight"],
        "pct_delayed":  G[a][b]["pct_delayed"],
        "trip_volume":  G[a][b]["trip_volume"],
    })



edge_df = pd.DataFrame(edge_records).sort_values("edge_betweenness", ascending=False)


print("TOP 10 STRUCTURALLY CRITICAL CORRIDORS:")
print(edge_df.head(10).to_string(index=False))

chronic = edge_df[(edge_df["median_delay"] > 1.2) &
                  (edge_df["trip_volume"]  >= 5)].copy()
chronic = chronic.sort_values("pct_delayed", ascending=False).reset_index(drop=True)
print(f"\nChronic delay corridors: {len(chronic):,}  "
      f"({len(chronic)/len(edge_df)*100:.1f}% of edges)")
print("\nTOP 10 CHRONIC DELAY CORRIDORS (by pct of trips delayed):")
print(chronic.head(10).to_string(index=False))

plt.figure(figsize=(10, 6))

top20 = node_df.head(20)
colors = ["#d62728" if i < 5 else "#4477aa" for i in range(20)]

plt.barh(
    top20["hub_id"][::-1],
    top20["bottleneck_rank"][::-1],
    color=colors[::-1]
)

plt.xlabel("Composite Bottleneck Rank (percentile)")
plt.title("Top 20 Hubs by Composite Rank\n(red = top 5)")

plt.tight_layout()
plt.savefig("stage7_top20_bottlenecks.png", dpi=150, bbox_inches="tight")
plt.show()

plt.figure(figsize=(8, 6))

sc = plt.scatter(
    node_df["betweenness"],
    node_df["sla_breach_score"],
    c=node_df["pagerank"],
    cmap="viridis",
    s=20 + node_df["out_degree"] * 1.5,
    alpha=0.7
)

plt.colorbar(sc, label="PageRank")

for _, row in node_df.head(5).iterrows():
    plt.annotate(
        row["hub_id"][-9:],
        (row["betweenness"], row["sla_breach_score"]),
        fontsize=7
    )

plt.xlabel("Betweenness")
plt.ylabel("SLA Breach Score")
plt.title(
    "Structural Risk × Current Pain\n"
    "(size = out-degree, colour = PageRank)"
)

plt.tight_layout()
plt.savefig("stage7_structural_vs_pain.png", dpi=150, bbox_inches="tight")
plt.show()

plt.figure(figsize=(8, 6))

plt.hist(
    node_df["clustering"],
    bins=30,
    color="#4477aa",
    edgecolor="white"
)

plt.axvline(
    node_df["clustering"].mean(),
    color="red",
    linestyle="--",
    label=f"mean = {node_df['clustering'].mean():.3f}"
)

plt.xlabel("Clustering Coefficient")
plt.ylabel("# Hubs")
plt.title("Local Density Distribution")
plt.legend()

plt.tight_layout()
plt.savefig("stage7_clustering_distribution.png", dpi=150, bbox_inches="tight")
plt.show()

#train node2vec

from node2vec import Node2Vec

EMBEDDING_DIM = 32           # match GraphSAGE so feature counts are comparable
WALK_LENGTH   = 30
NUM_WALKS     = 80
P_RETURN, Q_INOUT = 1.0, 0.5
WORKERS       = 2

print(f"Training Node2Vec  (dim={EMBEDDING_DIM}, walks={NUM_WALKS}x{WALK_LENGTH}, "
      f"p={P_RETURN}, q={Q_INOUT})  ~1–3 min")

n2v = Node2Vec(G_und,
               dimensions=EMBEDDING_DIM, walk_length=WALK_LENGTH,
               num_walks=NUM_WALKS, p=P_RETURN, q=Q_INOUT,
               workers=WORKERS, quiet=True)
n2v_model = n2v.fit(window=5, min_count=1, batch_words=4)

n2v_emb = {n: (n2v_model.wv[n] if n in n2v_model.wv else np.zeros(EMBEDDING_DIM))
           for n in G.nodes()}
print(f"Node2Vec embeddings ready for {len(n2v_emb):,} hubs.")


# GraphSAGE

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch_geometric.nn import SAGEConv
from torch_geometric.data import Data

torch.manual_seed(42)
np.random.seed(42)

# Convert NetworkX -> PyTorch Geometric Data

from sklearn.preprocessing import StandardScaler

CENTRALITY_LOOKUPS = {
    "betweenness"          : betweenness_n,
    "closeness"            : closeness_n,
    "pagerank"             : pagerank_n,
    "clustering"           : clustering_n,
    "in_degree"            : in_degree,
    "out_degree"           : out_degree,
    "weighted_in"          : weighted_in,
    "weighted_out"         : weighted_out,
    "sla_breach_score"     : sla_breach_score,
    "inbound_breach_score" : inbound_breach_score,
}

node_list  = list(G.nodes())
node_idx   = {n: i for i, n in enumerate(node_list)}
N_NODES    = len(node_list)
INPUT_DIM  = len(CENTRALITY_LOOKUPS)

X = np.zeros((N_NODES, INPUT_DIM), dtype=np.float32)
for j, (_, lookup) in enumerate(CENTRALITY_LOOKUPS.items()):
    X[:, j] = [lookup.get(n, 0.0) for n in node_list]
X = StandardScaler().fit_transform(X).astype(np.float32)

edge_pairs = [(node_idx[u], node_idx[v]) for u, v in G.edges()]
edge_index = torch.tensor(edge_pairs, dtype=torch.long).t().contiguous()
edge_weight = torch.tensor(
    [G[u][v]["weight"] for u, v in G.edges()], dtype=torch.float
)

data = Data(
    x          = torch.tensor(X, dtype=torch.float),
    edge_index = edge_index,
    edge_weight= edge_weight,
)
print(f"PyG Data:  nodes={data.num_nodes:,}  edges={data.num_edges:,}  "
      f"input feature dim={data.x.size(1)}")

#Define the GraphSAGE model
class GraphSAGE(nn.Module):
    def __init__(self, in_dim, hidden_dim, out_dim, dropout=0.2):
        super().__init__()
        self.conv1   = SAGEConv(in_dim,    hidden_dim, aggr="mean")
        self.conv2   = SAGEConv(hidden_dim, out_dim,   aggr="mean")
        self.dropout = dropout

    def forward(self, x, edge_index):
        h = F.relu(self.conv1(x, edge_index))                  # 1-hop mix
        h = F.dropout(h, p=self.dropout, training=self.training)
        h = self.conv2(h, edge_index)                          # 2-hop mix
        return h

#Unsupervised training: link prediction with negative sampling
SAGE_HIDDEN = 64
SAGE_OUT    = EMBEDDING_DIM   # = 32, matches Node2Vec
SAGE_EPOCHS = 200
LR          = 0.01
NEG_RATIO   = 1
BATCH_EDGES = 2048

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Training on: {device}")

model_sage = GraphSAGE(INPUT_DIM, SAGE_HIDDEN, SAGE_OUT).to(device)
optimizer  = torch.optim.Adam(model_sage.parameters(), lr=LR)
data_dev   = data.to(device)

n_edges_total = data_dev.edge_index.size(1)

print(f"GraphSAGE training  ({SAGE_EPOCHS} epochs, batch={BATCH_EDGES} edges)…")
loss_history = []
for epoch in range(SAGE_EPOCHS):
    model_sage.train()
    optimizer.zero_grad()

    z = model_sage(data_dev.x, data_dev.edge_index)            # (N, out_dim)

    pos_idx = torch.randint(0, n_edges_total, (BATCH_EDGES,), device=device)
    pos_src = data_dev.edge_index[0, pos_idx]
    pos_dst = data_dev.edge_index[1, pos_idx]

    neg_src = torch.randint(0, N_NODES, (BATCH_EDGES * NEG_RATIO,), device=device)
    neg_dst = torch.randint(0, N_NODES, (BATCH_EDGES * NEG_RATIO,), device=device)

    pos_logit = (z[pos_src] * z[pos_dst]).sum(dim=-1)
    neg_logit = (z[neg_src] * z[neg_dst]).sum(dim=-1)

    loss = (-F.logsigmoid(pos_logit).mean()
            -F.logsigmoid(-neg_logit).mean())
    loss.backward()
    optimizer.step()
    loss_history.append(loss.item())

    if epoch % 20 == 0 or epoch == SAGE_EPOCHS - 1:
        print(f"  epoch {epoch:>3d}   loss = {loss.item():.4f}")

# Extract final embeddings
model_sage.eval()
with torch.no_grad():
    sage_matrix = model_sage(data_dev.x, data_dev.edge_index).cpu().numpy()
sage_emb = {node_list[i]: sage_matrix[i] for i in range(N_NODES)}
print(f"GraphSAGE embeddings ready for {len(sage_emb):,} hubs.  "
      f"shape={sage_matrix.shape}")

# Loss curve
fig, ax = plt.subplots(figsize=(8, 3.5))
ax.plot(loss_history, color="#d62728", linewidth=1.5)
ax.set_xlabel("Epoch")
ax.set_ylabel("Link-prediction loss")
ax.set_title("GraphSAGE Training Loss (unsupervised link prediction)")
plt.tight_layout()
plt.savefig("stage8b_sage_loss.png", dpi=150, bbox_inches="tight")
plt.show()

# ---- 8b.F  FIX 2: Supervised GraphSAGE (delay-prediction task) -----------
import torch.nn.functional as F
from torch_geometric.nn import SAGEConv
import torch.nn as nn

print("\n" + "="*72)
print("Training SUPERVISED GraphSAGE (delay-prediction task)…")
print("="*72)

class SupervisedSAGE(nn.Module):
    def __init__(self, in_dim, hidden_dim, out_dim, dropout=0.3):
        super().__init__()
        self.conv1   = SAGEConv(in_dim,    hidden_dim, aggr="mean")
        self.conv2   = SAGEConv(hidden_dim, out_dim,   aggr="mean")
        self.pred    = nn.Linear(out_dim, 1)
        self.dropout = dropout

    def embed(self, x, edge_index):
        h = F.relu(self.conv1(x, edge_index))
        h = F.dropout(h, p=self.dropout, training=self.training)
        h = self.conv2(h, edge_index)
        return h

    def forward(self, x, edge_index):
        return self.pred(self.embed(x, edge_index)).squeeze()

# Supervised target: per-node mean segment_actual_time from training set
node_target_map = (
    df_train.groupby("source_center")["segment_actual_time"]
    .mean().to_dict()
)
node_targets = torch.tensor(
    [node_target_map.get(n, df_train["segment_actual_time"].median())
     for n in node_list],
    dtype=torch.float
)

# Normalise targets for stable training
y_mean = node_targets.mean()
y_std  = node_targets.std() + 1e-6
y_norm = (node_targets - y_mean) / y_std

data_sup = Data(
    x          = torch.tensor(X, dtype=torch.float),
    edge_index = edge_index,
    y          = y_norm,
)
data_sup_dev = data_sup.to(device)

SUP_SAGE_EPOCHS = 300
sup_model = SupervisedSAGE(INPUT_DIM, 64, SAGE_OUT).to(device)
sup_optimizer = torch.optim.Adam(sup_model.parameters(), lr=0.005, weight_decay=1e-4)

sup_loss_history = []
for epoch in range(SUP_SAGE_EPOCHS):
    sup_model.train()
    sup_optimizer.zero_grad()
    out = sup_model(data_sup_dev.x, data_sup_dev.edge_index)
    loss = F.mse_loss(out, data_sup_dev.y)
    loss.backward()
    sup_optimizer.step()
    sup_loss_history.append(loss.item())
    if (epoch + 1) % 50 == 0 or epoch == 0:
        print(f"  Epoch {epoch+1:>3d}/{SUP_SAGE_EPOCHS}  loss = {loss.item():.4f}")

# Extract supervised embeddings
sup_model.eval()
with torch.no_grad():
    sup_sage_matrix = sup_model.embed(data_sup_dev.x, data_sup_dev.edge_index).cpu().numpy()
sup_sage_emb = {node_list[i]: sup_sage_matrix[i] for i in range(N_NODES)}
print(f"Supervised GraphSAGE embeddings ready for {len(sup_sage_emb):,} hubs.  "
      f"shape={sup_sage_matrix.shape}")

# Supervised loss curve
fig, ax = plt.subplots(figsize=(8, 3.5))
ax.plot(sup_loss_history, color="#2ca02c", linewidth=1.5)
ax.set_xlabel("Epoch")
ax.set_ylabel("MSE loss (normalised delay)")
ax.set_title("Supervised GraphSAGE Training Loss (delay prediction)")
plt.tight_layout()
plt.show()

# t-SNE side-by-side
from sklearn.manifold import TSNE

n2v_matrix  = np.array([n2v_emb[n] for n in node_list])
sage_matrix = np.array([sage_emb[n] for n in node_list])
rank_lookup = dict(zip(node_df["hub_id"], node_df["bottleneck_rank"]))
hub_ranks   = np.array([rank_lookup.get(n, 0) for n in node_list])

print("Running t-SNE for both spaces…")
tsne_n2v  = TSNE(n_components=2, perplexity=30, init="pca",
                 learning_rate="auto", random_state=42).fit_transform(n2v_matrix)
tsne_sage = TSNE(n_components=2, perplexity=30, init="pca",
                 learning_rate="auto", random_state=42).fit_transform(sage_matrix)

fig, axes = plt.subplots(1, 2, figsize=(15, 6.5))
for ax, emb2d, title in [(axes[0], tsne_n2v,  "Node2Vec (random-walk benchmark)"),
                          (axes[1], tsne_sage, "GraphSAGE (PRIMARY)")]:
    sc = ax.scatter(emb2d[:, 0], emb2d[:, 1], c=hub_ranks, cmap="plasma",
                    s=18, alpha=0.85)
    plt.colorbar(sc, ax=ax, label="Composite bottleneck rank")
    for hub in top5_hubs["hub_id"]:
        if hub in node_list:
            i = node_list.index(hub)
            ax.annotate(hub[-9:], (emb2d[i, 0], emb2d[i, 1]),
                        fontsize=9, fontweight="bold")
    ax.set_title(title)
    ax.set_xlabel("t-SNE-1");  ax.set_ylabel("t-SNE-2")
plt.suptitle("Embedding spaces: Node2Vec vs GraphSAGE (colour = composite bottleneck rank)",
             fontsize=12, fontweight="bold", y=1.02)
plt.tight_layout()
plt.savefig("stage8c_n2v_vs_sage_tsne.png", dpi=150, bbox_inches="tight")
plt.show()

# Role discovery via k-means on GraphSAGE embeddings
# (We cluster the PRIMARY embedding space the personas the operations team
#  should care about are the ones that drive the headline ETA model.)
from sklearn.cluster import KMeans

K_ROLES = 6
km = KMeans(n_clusters=K_ROLES, n_init=10, random_state=42).fit(sage_matrix)
hub_role_sage = dict(zip(node_list, km.labels_))

role_summary = (
    node_df.assign(role=node_df["hub_id"].map(hub_role_sage))
           .groupby("role")
           .agg(n_hubs        = ("hub_id",          "size"),
                avg_betw      = ("betweenness",     "mean"),
                avg_pagerank  = ("pagerank",        "mean"),
                avg_in_deg    = ("in_degree",       "mean"),
                avg_out_deg   = ("out_degree",      "mean"),
                avg_sla_score = ("sla_breach_score","mean"),
                avg_clustering= ("clustering",      "mean"))
           .sort_values("avg_betw", ascending=False)
)
print("ROLE PERSONAS (k-means on GraphSAGE embeddings):")
print(role_summary.round(4).to_string())

# Attach BOTH embedding sets to df_train / df_test
# Centrality + Node2Vec + GraphSAGE features all become available downstream.
# RULE: graph and embeddings were trained on graph topology built from
# train-only corridor stats. Test rows pick up features by lookup -> no leak.

def _stack_emb(series, lookup, dim):
    arr = np.stack(series.map(lambda x: lookup.get(x, np.zeros(dim))).values)
    return arr

def _cosine_similarity_feature(df, emb_dict, dim, prefix):
    """Cosine similarity between source and destination embeddings."""
    from sklearn.preprocessing import normalize as sk_normalize
    emb_matrix = np.array([emb_dict.get(n, np.zeros(dim)) for n in node_list])
    emb_normed = sk_normalize(emb_matrix)
    norm_lookup = {n: emb_normed[i] for i, n in enumerate(node_list)}
    zeros = np.zeros(dim)
    df[f"cos_sim_{prefix}"] = [
        float(np.dot(norm_lookup.get(s, zeros), norm_lookup.get(d, zeros)))
        for s, d in zip(df["source_center"], df["destination_center"])
    ]
    return df

def attach_graph_features(df):
    df = df.copy()
    # Centrality features
    for name, lookup in CENTRALITY_LOOKUPS.items():
        df[f"src_{name}"] = df["source_center"].map(lookup).fillna(0).astype(float)
        df[f"dst_{name}"] = df["destination_center"].map(lookup).fillna(0).astype(float)
    # Node2Vec
    src_n2v = _stack_emb(df["source_center"],       n2v_emb,  EMBEDDING_DIM)
    dst_n2v = _stack_emb(df["destination_center"],  n2v_emb,  EMBEDDING_DIM)
    for i in range(EMBEDDING_DIM):
        df[f"src_n2v_{i}"]  = src_n2v[:, i]
        df[f"dst_n2v_{i}"]  = dst_n2v[:, i]
    # GraphSAGE (unsupervised)
    src_sage = _stack_emb(df["source_center"],      sage_emb, SAGE_OUT)
    dst_sage = _stack_emb(df["destination_center"], sage_emb, SAGE_OUT)
    for i in range(SAGE_OUT):
        df[f"src_sage_{i}"] = src_sage[:, i]
        df[f"dst_sage_{i}"] = dst_sage[:, i]
    # Supervised GraphSAGE embeddings
    src_sup = _stack_emb(df["source_center"],      sup_sage_emb, SAGE_OUT)
    dst_sup = _stack_emb(df["destination_center"], sup_sage_emb, SAGE_OUT)
    for i in range(SAGE_OUT):
        df[f"src_sup_sage_{i}"] = src_sup[:, i]
        df[f"dst_sup_sage_{i}"] = dst_sup[:, i]
    # Cosine similarity features
    df = _cosine_similarity_feature(df, n2v_emb,      EMBEDDING_DIM, "n2v")
    df = _cosine_similarity_feature(df, sage_emb,     SAGE_OUT,      "sage")
    df = _cosine_similarity_feature(df, sup_sage_emb, SAGE_OUT,      "sup_sage")
    return df

df_train = attach_graph_features(df_train)
df_test  = attach_graph_features(df_test)
print(f"df_train shape with all graph features: {df_train.shape}")
print(f"df_test  shape with all graph features: {df_test.shape}")

# Define feature sets
import xgboost as xgb
from sklearn.metrics import mean_absolute_error, r2_score, mean_squared_error

BASE_FEATURES = [
    "segment_osrm_time", "segment_osrm_distance", "osrm_speed_kmh",
    "departure_hour", "hour_sin", "hour_cos",
    "is_weekend", "is_night_shipment", "route_type_encoded",
    "departure_day_of_week", "cutoff_factor", "is_cutoff",
    "corridor_median_delay", "corridor_mean_delay", "corridor_delay_std",
    "corridor_trip_volume",  "corridor_pct_delayed",
]

CENTRALITY_FEATURES = BASE_FEATURES + [
    "src_betweenness","dst_betweenness", "src_closeness","dst_closeness",
    "src_pagerank","dst_pagerank", "src_clustering","dst_clustering",
    "src_in_degree","src_out_degree", "dst_in_degree","dst_out_degree",
    "src_weighted_in","dst_weighted_in", "src_weighted_out","dst_weighted_out",
    "src_sla_breach_score","dst_sla_breach_score",
    "src_inbound_breach_score","dst_inbound_breach_score",
]

N2V_FEATURES  = (CENTRALITY_FEATURES
                 + [f"src_n2v_{i}"  for i in range(EMBEDDING_DIM)]
                 + [f"dst_n2v_{i}"  for i in range(EMBEDDING_DIM)]
                 + ["cos_sim_n2v"])

SAGE_FEATURES = (N2V_FEATURES
                 + [f"src_sage_{i}" for i in range(SAGE_OUT)]
                 + [f"dst_sage_{i}" for i in range(SAGE_OUT)]
                 + ["cos_sim_sage"])

SUP_SAGE_FEATURES = (SAGE_FEATURES
                     + [f"src_sup_sage_{i}" for i in range(SAGE_OUT)]
                     + [f"dst_sup_sage_{i}" for i in range(SAGE_OUT)]
                     + ["cos_sim_sup_sage"])

TARGET = "segment_actual_time"   # minutes
y_train = df_train[TARGET].values
y_test  = df_test[TARGET].values

print(f"  Baseline                               : {len(BASE_FEATURES)}")
print(f"  + Centrality                           : {len(CENTRALITY_FEATURES)}")
print(f"  + Centrality + Node2Vec                : {len(N2V_FEATURES)}")
print(f"  + Centrality + N2V + GraphSAGE (unsup) : {len(SAGE_FEATURES)}")
print(f"  + Centrality + N2V + SAGE + SupSAGE    : {len(SUP_SAGE_FEATURES)}")


# Train all four models
def within_pct(pred, actual, tol=0.15):
    actual = np.asarray(actual, dtype=float)
    pred   = np.asarray(pred,   dtype=float)
    return (np.abs(pred - actual) / np.clip(actual, 1e-6, None) <= tol).mean() * 100

XGB_PARAMS = dict(n_estimators=400, max_depth=6, learning_rate=0.05,
                  subsample=0.9, colsample_bytree=0.9,
                  random_state=42, n_jobs=-1, verbosity=0)

results, models, predictions = {}, {}, {}
spec = [
    ("Baseline",                              BASE_FEATURES),
    ("+ Centrality",                          CENTRALITY_FEATURES),
    ("+ Centrality + Node2Vec",               N2V_FEATURES),
    ("+ Centrality + N2V + GraphSAGE(unsup)", SAGE_FEATURES),
    ("+ Cent + N2V + SAGE + SupervisedSAGE",  SUP_SAGE_FEATURES),
]
for name, feats in spec:
    m = xgb.XGBRegressor(**XGB_PARAMS)
    Xtr = df_train[feats].fillna(0).values
    Xte = df_test [feats].fillna(0).values
    m.fit(Xtr, y_train)
    pred = m.predict(Xte)

    mae  = mean_absolute_error(y_test, pred)
    rmse = np.sqrt(mean_squared_error(y_test, pred))
    r2   = r2_score(y_test, pred)
    w15  = within_pct(pred, y_test, 0.15)

    results[name]     = dict(mae=mae, rmse=rmse, r2=r2, within15=w15,
                             n_features=len(feats))
    models[name]      = m
    predictions[name] = pred
    print(f"{name:38s}  MAE={mae:7.2f} min   RMSE={rmse:7.2f}   R²={r2:.4f}   "
          f"Within-15%={w15:5.1f}%   ({len(feats)} features)")

# Decompose the Graph Advantage
B   = results["Baseline"]
C   = results["+ Centrality"]
N   = results["+ Centrality + Node2Vec"]
S   = results["+ Centrality + N2V + GraphSAGE(unsup)"]
SS  = results["+ Cent + N2V + SAGE + SupervisedSAGE"]

centrality_gain = (B["mae"] - C["mae"]) / B["mae"] * 100
n2v_gain        = (C["mae"] - N["mae"]) / C["mae"] * 100
sage_gain       = (N["mae"] - S["mae"]) / N["mae"] * 100
sup_sage_gain   = (S["mae"] - SS["mae"]) / S["mae"] * 100
total_advantage = (B["mae"] - SS["mae"]) / B["mae"] * 100

w15_centrality = C["within15"] - B["within15"]
w15_n2v        = N["within15"] - C["within15"]
w15_sage       = S["within15"] - N["within15"]
w15_sup_sage   = SS["within15"] - S["within15"]
w15_total      = SS["within15"] - B["within15"]

print("=" * 72)
print("GRAPH ADVANTAGE DECOMPOSITION  (lower MAE = better)")
print("=" * 72)
print(f"  Centrality gain (handcrafted)  : MAE −{centrality_gain:5.2f}%   |   Within-15% +{w15_centrality:.1f} pp")
print(f"  Node2Vec gain (random walks)   : MAE −{n2v_gain:5.2f}%   |   Within-15% +{w15_n2v:.1f} pp")
print(f"  GraphSAGE unsup (msg passing)  : MAE −{sage_gain:5.2f}%   |   Within-15% +{w15_sage:.1f} pp")
print(f"  Supervised SAGE (delay-trained): MAE −{sup_sage_gain:5.2f}%   |   Within-15% +{w15_sup_sage:.1f} pp     <-- HEADLINE")
print(f"  -----")
print(f"  TOTAL Graph Advantage          : MAE −{total_advantage:5.2f}%   |   Within-15% +{w15_total:.1f} pp")

#Comparison plots
fig, axes = plt.subplots(1, 4, figsize=(26, 5))
fig.suptitle("Stage 9 — Five-Model Benchmark", fontsize=13, fontweight="bold")
names = list(results.keys())
maes  = [results[n]["mae"]      for n in names]
rmses = [results[n]["rmse"]     for n in names]
r2s   = [results[n]["r2"]       for n in names]
w15s  = [results[n]["within15"] for n in names]
colors = ["#aec7e8", "#6baed6", "#1f77b4", "#ff7f0e", "#d62728"]
for ax, vals, title in zip(axes, [maes, rmses, r2s, w15s], ["MAE (min) ↓", "RMSE (min) ↓", "R² ↑", "Within-15% ↑"]):
    ax.bar(range(len(names)), vals, color=colors)
    ax.set_xticks(range(len(names)))
    ax.set_xticklabels([n.replace("+ ", "+\n").replace("Cent","Cent.") for n in names], fontsize=7, rotation=0)
    ax.set_title(title)
    for i, v in enumerate(vals):
        ax.text(i, v, f"{v:.2f}", ha="center", va="bottom", fontsize=8)
plt.tight_layout()
plt.show()

#Feature importance — grouped (PRIMARY model only)
best = models["+ Cent + N2V + SAGE + SupervisedSAGE"]
fi = pd.DataFrame({"feature": SUP_SAGE_FEATURES,
                   "importance": best.feature_importances_})

def categorise(f):
    if "_sup_sage_" in f: return "Supervised GraphSAGE (PRIMARY)"   # ← add this first
    if "_sage_" in f: return "GraphSAGE embedding (unsup)"
    if "_n2v_"  in f: return "Node2Vec embedding"
    if any(k in f for k in ["betweenness","closeness","pagerank","clustering",
                            "degree","weighted","breach"]):
        return "Graph centrality"
    if f.startswith("corridor_"): return "Corridor aggregate"
    if f.startswith("cos_sim_"):  return "Cosine similarity"        # ← add this too
    return "Trip / OSRM"

fi["category"] = fi["feature"].apply(categorise)
cat_imp = fi.groupby("category")["importance"].sum().sort_values(ascending=False)

print("Feature importance share by category (PRIMARY model):")
for cat, share in cat_imp.items():
    print(f"  {cat:32s}  {share*100:5.1f}%")

print("\nTop 15 individual features:")
print(fi.sort_values("importance", ascending=False)
        .head(15)[["feature","importance","category"]]
        .to_string(index=False))

# Corridor x route-type pivot + graph context
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import cross_val_score

cs = corridor_stats.copy()
parts = cs["corridor_id"].str.rsplit("_", n=1, expand=True)
cs["src_dst"]    = parts[0]
cs["route_type"] = parts[1]

pivot = cs.pivot_table(
    index   ="src_dst",
    columns ="route_type",
    values  =["corridor_median_delay","corridor_trip_volume","corridor_pct_delayed"],
    aggfunc ="first",
).reset_index()
pivot.columns = ["_".join(c).strip("_") for c in pivot.columns]
pivot = pivot.dropna(subset=["corridor_median_delay_FTL",
                             "corridor_median_delay_Carting"])

pivot["delay_advantage_ftl"] = (pivot["corridor_median_delay_Carting"]
                                - pivot["corridor_median_delay_FTL"])
pivot["ftl_is_faster"] = (pivot["delay_advantage_ftl"] > 0).astype(int)

sd = pivot["src_dst"].str.rsplit("_", n=1, expand=True)
pivot["src"] = sd[0]
pivot["dst"] = sd[1]
for col, lookup, side in [("src_betweenness", betweenness_n,    "src"),
                           ("dst_betweenness", betweenness_n,    "dst"),
                           ("src_pagerank",    pagerank_n,       "src"),
                           ("src_sla_score",   sla_breach_score, "src"),
                           ("src_in_degree",   in_degree,        "src"),
                           ("src_out_degree",  out_degree,       "src"),
                           ("dst_in_degree",   in_degree,        "dst")]:
    pivot[col] = pivot[side].map(lookup).fillna(0)

print(f"Corridors with both FTL and Carting variants: {len(pivot):,}")
print(f"FTL is faster on {pivot['ftl_is_faster'].mean()*100:.1f}% of them")

# Train classifier
FW_FEATURES = [
    "corridor_median_delay_Carting","corridor_trip_volume_Carting",
    "corridor_pct_delayed_Carting","corridor_median_delay_FTL",
    "corridor_trip_volume_FTL","corridor_pct_delayed_FTL",
    "src_betweenness","dst_betweenness","src_pagerank","src_sla_score",
    "src_in_degree","src_out_degree","dst_in_degree",
]
X_fw = pivot[FW_FEATURES].fillna(0)
y_fw = pivot["ftl_is_faster"]

clf = GradientBoostingClassifier(n_estimators=200, max_depth=3, random_state=42)
cv  = cross_val_score(clf, X_fw, y_fw, cv=5, scoring="accuracy")
print(f"FTL/Carting classifier — 5-fold CV accuracy: "
      f"{cv.mean()*100:.1f}% ± {cv.std()*100:.1f}%")
clf.fit(X_fw, y_fw)

fi_fw = (pd.DataFrame({"feature": FW_FEATURES,
                       "importance": clf.feature_importances_})
           .sort_values("importance", ascending=False))
print("\nClassifier feature importance:")
print(fi_fw.to_string(index=False))

# recommend(src, dst, hour, day_of_week)
# Uses the GraphSAGE-enhanced ETA model (Stage 9 PRIMARY) for the minutes
# estimate. All graph context features (centrality, Node2Vec, GraphSAGE) are
# stitched into the prediction row in the exact order training used.

PRIMARY_MODEL_NAME = "+ Cent + N2V + SAGE + SupervisedSAGE"

def _expected_eta(src, dst, hour, day_of_week, route_type):
    base = {
        "segment_osrm_time"     : 0,
        "segment_osrm_distance" : 0,
        "osrm_speed_kmh"        : 40,
        "departure_hour"        : hour,
        "hour_sin"              : np.sin(2*np.pi*hour/24),
        "hour_cos"              : np.cos(2*np.pi*hour/24),
        "is_weekend"            : int(day_of_week >= 5),
        "is_night_shipment"     : int(hour < 6 or hour >= 22),
        "route_type_encoded"    : int(route_type == "FTL"),
        "departure_day_of_week" : day_of_week,
        "cutoff_factor"         : 1.0,
        "is_cutoff"             : 0,
    }
    cid  = f"{src}_{dst}_{route_type}"
    crow = corridor_stats[corridor_stats["corridor_id"] == cid]
    if len(crow):
        base.update({
            "corridor_median_delay": float(crow["corridor_median_delay"].iloc[0]),
            "corridor_mean_delay"  : float(crow["corridor_mean_delay"].iloc[0]),
            "corridor_delay_std"   : float(crow["corridor_delay_std"].iloc[0] or 0),
            "corridor_trip_volume" : float(crow["corridor_trip_volume"].iloc[0]),
            "corridor_pct_delayed" : float(crow["corridor_pct_delayed"].iloc[0]),
        })
    else:
        for c in ["corridor_median_delay","corridor_mean_delay","corridor_delay_std",
                  "corridor_trip_volume","corridor_pct_delayed"]:
            base[c] = float(corridor_stats[c].median())

    for name, lookup in CENTRALITY_LOOKUPS.items():
        base[f"src_{name}"] = float(lookup.get(src, 0))
        base[f"dst_{name}"] = float(lookup.get(dst, 0))

    src_n2v      = n2v_emb.get(src,      np.zeros(EMBEDDING_DIM))
    dst_n2v      = n2v_emb.get(dst,      np.zeros(EMBEDDING_DIM))
    src_sage     = sage_emb.get(src,     np.zeros(SAGE_OUT))
    dst_sage     = sage_emb.get(dst,     np.zeros(SAGE_OUT))
    src_sup_sage = sup_sage_emb.get(src, np.zeros(SAGE_OUT))
    dst_sup_sage = sup_sage_emb.get(dst, np.zeros(SAGE_OUT))
    for i in range(EMBEDDING_DIM):
        base[f"src_n2v_{i}"]      = float(src_n2v[i])
        base[f"dst_n2v_{i}"]      = float(dst_n2v[i])
    for i in range(SAGE_OUT):
        base[f"src_sage_{i}"]     = float(src_sage[i])
        base[f"dst_sage_{i}"]     = float(dst_sage[i])
        base[f"src_sup_sage_{i}"] = float(src_sup_sage[i])
        base[f"dst_sup_sage_{i}"] = float(dst_sup_sage[i])
    # Cosine similarities
    def _cos(a, b):
        na, nb = np.linalg.norm(a), np.linalg.norm(b)
        if na < 1e-8 or nb < 1e-8: return 0.0
        return float(np.dot(a, b) / (na * nb))
    base["cos_sim_n2v"]      = _cos(src_n2v,      dst_n2v)
    base["cos_sim_sage"]     = _cos(src_sage,     dst_sage)
    base["cos_sim_sup_sage"] = _cos(src_sup_sage, dst_sup_sage)
    row = np.array([base[c] for c in SUP_SAGE_FEATURES]).reshape(1, -1)
    return float(models[PRIMARY_MODEL_NAME].predict(row)[0])


def recommend(src, dst, hour=10, day_of_week=2):
    have_both = ((pivot["src"] == src) & (pivot["dst"] == dst)).any()
    if have_both:
        prow  = pivot[(pivot["src"] == src) & (pivot["dst"] == dst)].iloc[0]
        x_clf = prow[FW_FEATURES].values.reshape(1, -1).astype(float)
        ftl_prob = float(clf.predict_proba(x_clf)[0, 1])
        ftl_pick = ftl_prob >= 0.5
    else:
        ftl_only     = (corridor_stats["corridor_id"] == f"{src}_{dst}_FTL").any()
        carting_only = (corridor_stats["corridor_id"] == f"{src}_{dst}_Carting").any()
        if   ftl_only and not carting_only:    ftl_pick, ftl_prob = True,  0.55
        elif carting_only and not ftl_only:    ftl_pick, ftl_prob = False, 0.55
        else:
            ftl_pick = betweenness_n.get(src, 0) > np.median(list(betweenness_n.values()))
            ftl_prob = 0.55 if ftl_pick else 0.45

    rec   = "FTL" if ftl_pick else "Carting"
    eta_m = _expected_eta(src, dst, hour, day_of_week, rec)
    cid   = f"{src}_{dst}_{rec}"
    crow  = corridor_stats[corridor_stats["corridor_id"] == cid]
    risk  = (float(crow["corridor_pct_delayed"].iloc[0])
             if len(crow) else float(corridor_stats["corridor_pct_delayed"].median()))

    return {
        "src"                 : src,
        "dst"                 : dst,
        "hour"                : hour,
        "day_of_week"         : day_of_week,
        "recommended_route"   : rec,
        "confidence"          : round(max(ftl_prob, 1 - ftl_prob), 3),
        "expected_eta_minutes": round(eta_m, 1),
        "expected_delay_risk" : round(risk, 3),
        "model_used"          : PRIMARY_MODEL_NAME,
    }

# Worked examples
sample_chronic = chronic.head(1).iloc[0]
example_ods = [
    (sample_chronic["src"], sample_chronic["dst"]),
    (top5_hubs.iloc[0]["hub_id"], list(G.successors(top5_hubs.iloc[0]["hub_id"]))[0]),
    (pivot.sort_values("delay_advantage_ftl", ascending=False).iloc[0]["src"],
     pivot.sort_values("delay_advantage_ftl", ascending=False).iloc[0]["dst"]),
]
print("Recommendation samples (hour=10, weekday) — using GraphSAGE-enhanced ETA model:\n")
for src, dst in example_ods:
    out = recommend(src, dst, hour=10, day_of_week=2)
    print(f"  {src}  →  {dst}")
    for k, v in out.items():
        if k in ("src", "dst"): continue
        print(f"      {k:22s}: {v}")
    print()

"""
---
## Stage 11 — Network Operations Strategy Memo (D5)

The cell below produces every number the memo cites — and it pulls those
numbers from the **GraphSAGE-enhanced** ETA model and the GraphSAGE-derived
hub clusters. The memo prose follows in the next markdown cell.
"""

# ---- 11.A  Memo supporting numbers (GraphSAGE-anchored) -------------------
print("=" * 72)
print("NETWORK OPERATIONS STRATEGY MEMO — SUPPORTING NUMBERS")
print("(All ETA-model figures cite the GraphSAGE-enhanced PRIMARY model.)")
print("=" * 72)

# 1) Network state
total_corridors = len(corridor_stats)
sla_breach_corr = (corridor_stats["corridor_median_delay"] > 1.2).sum()
print("\n[1] NETWORK STATE")
print(f"   Facilities (nodes)        : {G.number_of_nodes():,}")
print(f"   Corridors (edges)         : {G.number_of_edges():,}")
print(f"   SLA-breaching corridors   : {sla_breach_corr:,} / {total_corridors:,} "
      f"({sla_breach_corr/total_corridors*100:.1f}%)")
print(f"   Trips with SLA breach     : {df_train['is_delayed'].mean()*100:.1f}% in train")

# 2) Top 5 bottleneck hubs
top5_share = top5_hubs["sla_breach_score"].sum() / node_df["sla_breach_score"].sum()
top3_share = top5_hubs.head(3)["sla_breach_score"].sum() / node_df["sla_breach_score"].sum()
print("\n[2] TOP 5 BOTTLENECK HUBS")
print(top5_hubs[["hub_id","betweenness","sla_breach_score",
                 "in_degree","out_degree","pagerank"]]
      .to_string(index=False))
print(f"\n   Top-3 hubs hold {top3_share*100:.1f}% of network-wide SLA breach score.")
print(f"   Top-5 hubs hold {top5_share*100:.1f}% of network-wide SLA breach score.")

# 3) Intervention math
ASSUMED_DELAY_REDUCTION = 0.25
projected_sla_reduction = top3_share * ASSUMED_DELAY_REDUCTION

REV_BASE_CR        = 10_000
REV_AT_RISK_PER_PP = 0.006 * REV_BASE_CR     # 60 Cr / pp at 0.6% revenue at risk per pp
late_pp_reduction    = df_train["is_delayed"].mean() * 100 * projected_sla_reduction
revenue_recovered_cr = late_pp_reduction * REV_AT_RISK_PER_PP

print("\n[3] PROJECTED IMPACT — upgrading top 3 bottleneck hubs")
print(f"   Assumed delay reduction at upgraded hubs : {ASSUMED_DELAY_REDUCTION*100:.0f}%")
print(f"   Projected SLA breach reduction (network) : {projected_sla_reduction*100:.1f}%")
print(f"   Late-delivery rate ↓                     : {late_pp_reduction:.2f} pp")
print(f"   Revenue-at-risk recovered (annualised)   : INR ~{revenue_recovered_cr:,.1f} Cr")
print(f"   (Assumes INR {REV_BASE_CR:,} Cr revenue base, "
      f"{REV_AT_RISK_PER_PP:.0f} Cr at risk per pp of late deliveries.)")

# 4) ETA model — the headline is the GraphSAGE-enhanced model
print("\n[4] ETA MODEL — Five-Model Benchmark")
for name, res in results.items():
    flag = "  <-- PRIMARY" if name == PRIMARY_MODEL_NAME else ""
    print(f"   {name:42s}  MAE={res['mae']:6.2f} min   "
          f"R²={res['r2']:.4f}   Within-15%={res['within15']:5.1f}%{flag}")
print(f"\n   Centrality gain   : MAE −{centrality_gain:.1f}%   Within-15% +{w15_centrality:.1f} pp")
print(f"   Node2Vec gain     : MAE −{n2v_gain:.1f}%   Within-15% +{w15_n2v:.1f} pp")
print(f"   GraphSAGE(unsup)  : MAE −{sage_gain:.1f}%   Within-15% +{w15_sage:.1f} pp")
print(f"   Supervised SAGE   : MAE −{sup_sage_gain:.1f}%   Within-15% +{w15_sup_sage:.1f} pp   <-- HEADLINE")
print(f"   TOTAL Graph Adv.  : MAE −{total_advantage:.1f}%   Within-15% +{w15_total:.1f} pp")