import streamlit as st
import sys
import os

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from utils.data_loader import load_csv, load_json
from components.aesthetics import apply_custom_css
from components.charts import plot_embeddings_tsne

st.set_page_config(page_title="Graph Embeddings Lab", page_icon="🧬", layout="wide")
apply_custom_css()

st.title("Graph Embeddings Lab")
st.markdown("Visualizing high-dimensional node representations generated by representation learning algorithms.")

node2vec_df = load_csv("node2vec_embeddings.csv")
graphsage_df = load_csv("graphsage_embeddings.csv")
sup_sage_df = load_csv("sup_sage_embeddings.csv")
node_df = load_csv("node_df.csv")

if node2vec_df.empty or graphsage_df.empty or sup_sage_df.empty:
    st.warning("Embeddings not found. Please run the artifact extraction script.")
    st.stop()
    
# Clean index if needed
if "hub_id" in node2vec_df.columns: node2vec_df.set_index("hub_id", inplace=True)
if "hub_id" in graphsage_df.columns: graphsage_df.set_index("hub_id", inplace=True)
if "hub_id" in sup_sage_df.columns: sup_sage_df.set_index("hub_id", inplace=True)

ranks = []
for hub in node2vec_df.index:
    rank_val = node_df[node_df["hub_id"] == hub]["bottleneck_rank"].values
    ranks.append(rank_val[0] if len(rank_val) > 0 else 0)

st.markdown("""
### The Representation Progression
1. **Node2Vec**: 32-D vectors learned via random walks. Captures structure, but ignores hub features.
2. **GraphSAGE (Unsupervised)**: 32-D vectors learned via message passing. Combines the hub's features with neighbors.
3. **Supervised GraphSAGE**: Explicitly trained to predict node-level delay. **This is our primary representation.**
""")

st.markdown("---")
c1, c2, c3 = st.columns(3)

with c1:
    st.markdown("#### Node2Vec")
    st.caption("Random-walk baseline.")
    fig1 = plot_embeddings_tsne(node2vec_df, ranks, title="Node2Vec")
    st.plotly_chart(fig1, use_container_width=True)

with c2:
    st.markdown("#### GraphSAGE (Unsup)")
    st.caption("Message-passing model without delay labels.")
    fig2 = plot_embeddings_tsne(graphsage_df, ranks, title="GraphSAGE (Unsup)")
    st.plotly_chart(fig2, use_container_width=True)

with c3:
    st.markdown("#### Supervised SAGE (PRIMARY)")
    st.caption("Explicitly trained on delay. Notice the sharp cluster of high-risk nodes (yellow/bright).")
    fig3 = plot_embeddings_tsne(sup_sage_df, ranks, title="Supervised SAGE")
    st.plotly_chart(fig3, use_container_width=True)

st.info("💡 **Why this matters**: The Supervised GraphSAGE model perfectly separates the chronically delayed regions of the network from the healthy regions, giving the downstream XGBoost model a massive predictive advantage.")
