import streamlit as st
import os
import sys

# Ensure components and utils are importable
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from components.aesthetics import apply_custom_css

st.set_page_config(
    page_title="Graph ML Intelligence | Delhivery",
    page_icon="🕸️",
    layout="wide",
    initial_sidebar_state="expanded",
)

# Apply global styling
apply_custom_css()

# Sidebar Navigation Configuration
st.sidebar.markdown("""
<div style='text-align: center; margin-bottom: 20px;'>
    <h2 style='margin: 0; padding: 0;'>Delhivery</h2>
    <p style='color: #94a3b8; font-size: 0.9rem; margin-top: 5px;'>Graph Network Intelligence</p>
</div>
""", unsafe_allow_html=True)

st.sidebar.markdown("---")

st.sidebar.markdown("""
**Portfolio Product:**
This platform demonstrates the application of Graph Representation Learning (GraphSAGE, Node2Vec) and Network Centrality metrics combined with XGBoost to solve logistics ETA underestimations.
""")

st.sidebar.markdown("---")
st.sidebar.caption("© 2026 Data Science & ML Engineering Team")

# Redirection or landing logic can be placed here if needed
if __name__ == "__main__":
    st.markdown("""
    # 🕸️ Welcome to the Graph ML Network Intelligence Platform
    
    👈 Please select a module from the sidebar to begin exploring the logistics network.
    
    ### Available Modules:
    1. **Executive Overview**: High-level network metrics and simulated business impact of upgrading bottleneck hubs.
    2. **Network Explorer**: Interactive structural visualization of the hub and corridor network.
    3. **Bottleneck Intelligence**: Deep-dive into structural risk vs operational pain.
    4. **Graph Embeddings Lab**: Visualize high-dimensional representations generated by Node2Vec and GraphSAGE.
    5. **ETA Prediction Engine**: Live ETA inference powered by the GraphSAGE-enhanced XGBoost model.
    6. **Model Benchmarks**: Ablation study demonstrating the precise value added by message-passing over standard features.
    7. **Model Explainability**: Feature importance analysis and SHAP-like insights.
    8. **Technical Architecture**: System flow and metadata for the ML pipelines.
    """)
    
    # Render badges
    st.markdown("""
    <div style="display: flex; gap: 10px; margin-top: 20px;">
        <span class="badge badge-blue">GraphSAGE</span>
        <span class="badge badge-green">XGBoost</span>
        <span class="badge badge-amber">PyTorch Geometric</span>
        <span class="badge badge-red">Plotly</span>
    </div>
    """, unsafe_allow_html=True)
